### ISSUE TITLE
Activity Log breaks SSO Plugin

### ISSUE THREAD

**Issue by andrew-barnett** [pojome/activity-log#113]
Using [miniOrange SSO using SAML 2.0](https://wordpress.org/plugins/miniorange-saml-20-single-sign-on/) v11.1.4 (aka v4.8.33) for authentication. When Activity Log 2.4.0 is activated, the SAML flow fails to respond to the final POST with a 302 redirect, instead returning a 200 with blank body.

I'm wondering what part of the Activity Log hooking mechanism is interfering with the authentication flow of the SAML plugin.

This is WordPress 4.9.1.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue. 

Thanks!
