### ISSUE TITLE
Email logs Feature

### ISSUE THREAD

**Issue by ronoliverclarin** [pojome/activity-log#118]
All email notification to customers/admin from wordpress should save. Is this included or possible?

**Comment by bkno** [comment]
+1

Logging emails would be incredibly useful.

**Comment by AlecRust** [comment]
This would be great, and avoid the need for a separate plugin like [Mail logging](https://wordpress.org/plugins/wp-mail-catcher/).

**Comment by arielk** [comment]
Done by https://github.com/pojome/activity-log/pull/206

Thanks for your feedback!
