### ISSUE TITLE
Feature Request: Write to file

### ISSUE THREAD

**Issue by fredclown** [pojome/activity-log#122]
Please consider adding the option to write the log to file along with log rotation. I realize there is the Export to CSV, but that requires a human to manually export it. If the log were written to disk it could be incorporated into many automation products that could provide advanced searching/correlation/alerting (ex. Splunk, Elastic Stack).

**Comment by fredclown** [comment]
Is development on this plugin dead? I see no comments  on most of the issues here ... even just to say "Not going to do". I'm not trying to be snarky, I'm just honestly wondering if this plugin has been abandoned.

**Comment by arielk** [comment]
Yes, I know it's a long long time, but we are still maintaining the code and we trying to keep it simple and easy. You can integrate to external DB's through the database directly.

Thank you for your feedback!
