### ISSUE TITLE
Feature Request , exclude failed loging attempts

### ISSUE THREAD

**Issue by StefanoWP** [pojome/activity-log#125]
Hi there! Thanks for the awesome plugin.
I was wondering if this is possible, because the plugin logs the WordPress failed logins, in a future release, if you could add a function to disable the login failed attempts that would be awesome. I just opened a support request at [wordpress.org](https://wordpress.org/support/topic/possible-database-crash-in-case-of-ddos-attach/). The issue we have right now, is that the failed login attempts when a simple logging attack is happening to a website, the logs flood the database and take down the website (DDoS-ing the website). If we could remove this function (writing the failed attempts on DB) we can use this plugin for good. I made a fast search in the code but I couldn't locate any function that i could remove for now. any help, or adding this option in the future, if it's possible, that could help a lot all.! thanks and let me know your thoughts!
[screenshot 1](https://imgur.com/G8wwsG6)
[screenshot 2](https://i.imgur.com/yALNhHg.png)

**Comment by tomslominski** [comment]
+1 to this. I already have a separate plugin for dealing with repeated log-in attempts, with its own logging system for log-in related events. I know the issue on WordPress.org is marked as solved, but I don't think commenting out a line of code really cuts the mustard, given the plugin is inevitably going to be updated! So it would be nice to have an option/filter to disable certain events being logged.

**Comment by arielk** [comment]
This option has been added in Activity Log v2.7.0

Feel free to update and thanks for the feedback!

Thanks!
