### ISSUE TITLE
Feature Request: Ability to hide password from the log on a failed login attempt

### ISSUE THREAD

**Issue by Picksley** [pojome/activity-log#128]
I'd like to add the possibility of being able to have an option to disable output of a failed login attempt?

I don't like the idea of having admins or devs to see the plain text of the password of an attempted login. It's quite a large security risk and not too difficult to guess what the correct password would be

**Comment by arielk** [comment]
We do not save the wrong password at all, only the username. Can you please add a screenshot of what you mean?
