### ISSUE TITLE
Time is wrong Export CSV diffirent Backend page

### ISSUE THREAD

**Issue by nrawut** [pojome/activity-log#134]
When login to backend and goto 
Menu Activity Log --> Show page as
1. Right time as setting in Wordpress
1 min ago
10/08/2019 13:50:46

But when click Export to CSV Button
1. Wrong time, it give me 
10-08-19 20:50

I'm use Thailand hosting UTC+7

**Comment by arielk** [comment]
A long time, but I can not reproduce the problem so I close the issue, feel free to open if the issue still exists, thanks

**Comment by nrawut** [comment]
Thank you very much for your reply. ^ ^
Regards,
