### ISSUE TITLE
Dashboard Errors

### ISSUE THREAD

**Issue by reinhardjung** [pojome/activity-log#136]
Hi

I got some Errors in my Dashboard. Any Idea why and how i can fix it?
![Bildschirmfoto 2020-04-02 um 07 53 12](https://user-images.githubusercontent.com/298616/78215090-03cfab00-74b7-11ea-80c7-9c41c3d8eebc.png)

Thanx a lot 4 any Help

**Comment by arielk** [comment]
Sorry, but it's not belong to our plugin.
