### ISSUE TITLE
'view_all_aryo_activity_log' fallback capability

### ISSUE THREAD

**Issue by pedalmeat** [pojome/activity-log#139]
Maybe i am missing something but there is a capabilitycheck for 'view_all_aryo_activity_log' in create_admin_menu() but falls back to 'edit_pages' capability. If the check returns true the user is able to see the Activity Log menu, if returns false you can se the menu item still as the most users are in a role that can 'edit_pages'.

**Comment by KingYes** [comment]
Fixed by: https://github.com/pojome/activity-log/issues/139
