### ISSUE TITLE
Fatal error under reproducible condition

### ISSUE THREAD

**Issue by sanzeeb3** [pojome/activity-log#145]
It looks like `get_user_by()` can be called earlier than it has been defined. So, the following error can exist under reproducible conditions.
 

> PHP Fatal error: Uncaught Error: Call to undefined function get_user_by() in /home/***/domains/example.com/public_html/wp-content/plugins/aryo-activity-log/classes/class-aal-api.php

**Comment by arielk** [comment]
Hi,

This issue has been resolved in the recently updates. Feel free to update and let me know if it solve your issue. 

Thanks!
