### ISSUE TITLE
E_ERROR caused by get_id() in version 2.7.0

### ISSUE THREAD

**Issue by gbakeman** [pojome/activity-log#147]
I just received an email from my site about an uncaught error generated by Activity Log. Around that time, I was installing SiteGround's Security plugin:

WordPress version 5.8
Current theme: The7 (version 9.16.0)
Current plugin: Activity Log (version 2.7.0)
PHP version 7.4.23

Error Details
=============
An error of type E_ERROR was caused in line 31 of the file /public_html/wp-content/plugins/aryo-activity-log/classes/class-aal-integration-woocommerce.php.
Error message: Uncaught Error: Call to a member function get_id() on int in /public_html/wp-content/plugins/aryo-activity-log/classes/class-aal-integration-woocommerce.php:31
```
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(303): AAL_Integration_WooCommerce->wc_get_settings_pages(Array)
#1 /public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(62): apply_filters('woocommerce_get...', Array)
#3 /public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(175): WC_Admin_Settings::get_settings_pages()
#4 /public_html/wp-includes/class-wp-hook.php(303): WC_API->register_wp_admin_settings(Object(WP_REST_Server))
#5 /public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL,
```

**Comment by arielk** [comment]
Please uninstall SiteGround Security plugin or send the error to the SG plugin author,

Thanks
