### ISSUE TITLE
Feature request: Ability to add manual log entries

### ISSUE THREAD

**Issue by scottdavidcraig** [pojome/activity-log#148]
Hey folks, 

Love what you've built.

We have a feature request: The ability to add a manual entries to the activity log.

We have sites with  multiple people working on them. and it would be really helpful if people were able to put in a manual log entry describing the changes they had made. Giving some context that explains what the changes mean.

What to you think?

**Comment by catbadger** [comment]
there is 100% a thread where this is dicussed.
something like 
```php
 aal_insert_log( array(
        'action'         => "Invoicing-".$action,
        'object_type'    => 'InvoiceAccessRestictor',
        'object_subtype' => "IAR Info",
        'object_name'    => $name,
    ) );
```
