### ISSUE TITLE
Slow queries when looking up events

### ISSUE THREAD

**Issue by sullysmall** [pojome/activity-log#163]
We have a log table with millions of rows, looking for a duplicate event (class-aal-api.php:106) adds a big load onto the database.

I found that adding indexes for `object_name` and `user_id` has helped to speed up the query.

It might be useful for you to add these indexes too.

**Comment by arielk** [comment]
This issue has been resolved in the recently updates. Feel free to update and let me know if it solve your issue. 

Thanks!
