### ISSUE TITLE
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated.

### ISSUE THREAD

**Issue by oldrup** [pojome/activity-log#175]
Hey

Testing activity-log with WordPress 6.2 beta 2 and PHP 8.1- so, bleeding edge, kinda. 

When viewing the activity log, the following warning is displayed: 

`Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /home/sustain2/example.com/wp-admin/includes/class-wp-list-table.php on line 1343`

Screenshot:
![image](https://user-images.githubusercontent.com/17141205/219382777-fbf5da5e-a424-4f4e-b845-3e5b89411341.png)

Besides that, the plugin seems to work fine with WP 6.2 and PHP 8.1

I'm unable to figure out it the warning is WordPress core related – but now you know it exists :)
Bjarne

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists feel free to reopen the issue. 

Thanks!
