### ISSUE TITLE
Username Display for login attempts

### ISSUE THREAD

**Issue by wpadriaan** [pojome/activity-log#176]
Hi, great plugin and thank you! I just noticed a minor issue, not sure if it affects others but all our usernames are set as users email - when a 'failed login' is tracked it shows the user email in the 'username' column I assume that they used as the username when attempting to login - however when they successfully login it displays the username as the slug or permalink - ie the @ and . are removed/replaced - I can tell it's the same user as the IP matches between a success and fail but it's confusing when trying to filter on a users email as it will only show the failures. Thanks

**Comment by KingYes** [comment]
It's a different log, so I can't use it.
