### ISSUE TITLE
Activity Log no longer recording website activity

### ISSUE THREAD

**Issue by markcass8888** [pojome/activity-log#177]
Hi, My hosting company has recently migrated my website to a new hosting package and this has caused a number of problems and critical errors on my website. such as:
1 My Activity log is no longer recording any website activity since the migration 
and
2. When i deactivated the Activity log plugin it caused the following critical error (please note a number of the plugins - WP Rocket, Rank Math are triggering the critical error. Hopefully this might be a clue to the problem, but my main question to you is why the plugin is no longer recording site activity?
Please assist.

**Comment by KingYes** [comment]
I would appreciate it if you could add logs to your situation. I see it's an old ticket; feel free to re-open it.
