### ISSUE TITLE
Delete logs after x days not working

### ISSUE THREAD

**Issue by joldnl** [pojome/activity-log#178]
I have set up deleting old logs after 30 days, but if I check the oldest log entries, they are more than a year old. Saving the setting again does not result in deleted old log entries. Also deactivating and reactivating the plugin does not result in a cleaned up list of logs.

FIY: I've got the plugin network installed on a multisite setup.

I've got latest wordpress and activity log versions installed

**Comment by KingYes** [comment]
Hi @joldnl 
It should be fixed by this PR: https://github.com/pojome/activity-log/pull/187

Thanks
