### ISSUE TITLE
N/A user log

### ISSUE THREAD

**Issue by Maxbonesso** [pojome/activity-log#183]
Hi, in the last days I noticed that the activity log is logging some activity of deleting users or posts by n/a users. Can you give me any help? The IP are from an external server, so is there an hacking in act? Or is something done from an internal user that is not loggable?
An example of the action is:
2023/06/28 07:22:44 AM,unknown,5x.xx.xx.xx1,Users,Profile,bxxxx-xxxxn,Deleted

When the plugin registers this type of action, what information is it unable to obtain so as not to find a username?
When a user fails to login as admin it logs it as N/A, but in this case the action was done, so I would like to understand the situation better.
Thank you

**Comment by StefsterNYC** [comment]
Often the app is logging N/As that are typically from the hosting company you are on. However, deleting of posts and what not is hard to tell without seeing anything. Like a screenshot or what not. A scheduled action from the server side can be a N/A as well. 

A lot of times hackers will disable the Activity Log app, but again hard to tell without seeing something.

**Comment by Maxbonesso** [comment]
An example is this:
2023/06/28 07:18:32   AM,unknown,52.16.210.181,Users,Profile,birgit,Deleted
2023/06/28 07:18:33   AM,unknown,52.16.210.181,Posts,recipes,"Berry Tonic   Mocktail",Deleted
2023/06/28 07:18:34   AM,unknown,52.16.210.181,Posts,recipes,"Cold Brew Protein   Smoothie",Deleted
2023/06/28 07:18:35   AM,unknown,52.16.210.181,Posts,recipes,"Tiramisu Martini",Deleted
2023/06/28 07:18:36   AM,unknown,52.16.210.181,Posts,recipes,"Candy Corn Latte",Deleted
2023/06/28 07:18:36   AM,unknown,52.16.210.181,Posts,recipes,"Cold Brew Negroni",Deleted
2023/06/28 07:18:37   AM,unknown,52.16.210.181,Posts,discover,"DÃ©couvrez le cafÃ© bon,   durable et Ã©quitable Â ",Deleted
2023/06/28 07:18:37   AM,unknown,52.16.210.181,Posts,discover,"Ontdek goede, zuivere en   eerlijke koffie",Deleted
2023/06/28 07:18:37   AM,unknown,52.16.210.181,Posts,recipes,"Candy Corn Latte",Deleted
2023/06/28 07:18:38   AM,unknown,52.16.210.181,Posts,discover,"CafÃ©, Dolce Vita italien:   Leccese et autres inspirations de cafÃ©",Deleted
2023/06/28 07:18:38   AM,unknown,52.16.210.181,Posts,discover,"Svenja Tinzmann : un cafÃ©   Ã©quitable a meilleur gout",Deleted
2023/06/28 07:18:39   AM,unknown,52.16.210.181,Posts,discover,"Svenja Tinzmann: duurzame   koffie smaakt beter",Deleted
2023/06/28 07:18:40   AM,unknown,52.16.210.181,Posts,discover,"Dan Dunne : des grains Ã    la tasse professionnelle",Deleted
2023/06/28 07:18:40   AM,unknown,52.16.210.181,Posts,discover,"Dan Dunne: van koffieboon tot   professioneel kopje koffie",Deleted
2023/06/28 07:18:41   AM,unknown,52.16.210.181,Posts,discover,"Alexis Gagnaire : lâ€™art de la   torrÃ©faction",Deleted
2023/06/28 07:18:41   AM,unknown,52.16.210.181,Posts,discover,"Alexis Gagnaire: de kunst van   het koffiebranden",Deleted
2023/06/28 07:18:42   AM,unknown,52.16.210.181,Posts,discover,"De la ferme de Laura Ã    votre tasse",Deleted
2023/06/28 07:18:43   AM,unknown,52.16.210.181,Posts,discover,"Van Laura&#8217
2023/06/28 07:18:43   AM,unknown,52.16.210.181,Posts,recipes,"Espresso oat breakfast   smoothie",Deleted
2023/06/28 07:18:43   AM,unknown,52.16.210.181,Posts,recipes,"Smoothie espresso Ã    l&#8217
2023/06/28 07:18:44   AM,unknown,52.16.210.181,Posts,discover,"Koffie &#038
2023/06/28 07:18:44   AM,unknown,52.16.210.181,Posts,discover,"Quand le cafÃ© devient   floral",Deleted
2023/06/28 07:18:45   AM,unknown,52.16.210.181,Posts,recipes,"Latte de lavande",Deleted
2023/06/28 07:18:45   AM,unknown,52.16.210.181,Posts,recipes,"Macchiato Ã  l&#8217
2023/06/28 07:18:46   AM,unknown,52.16.210.181,Posts,recipes,"CafÃ© Ã  la rose   froide",Deleted
2023/06/28 07:18:46   AM,unknown,52.16.210.181,Posts,recipes,"Zoete haver   Macchiato",Deleted
2023/06/28 07:18:47   AM,unknown,52.16.210.181,Posts,recipes,"Koude rozen koffie",Deleted
2023/06/28 07:18:47   AM,unknown,52.16.210.181,Posts,recipes,"Lavendel Latte",Deleted
2023/06/28 07:18:48   AM,unknown,52.16.210.181,Posts,discover,"Un cafÃ© aux saveurs   tropicales",Deleted
2023/06/28 07:18:48   AM,unknown,52.16.210.181,Posts,recipes,"Alpro Latte",Deleted
2023/06/28 07:18:49   AM,unknown,52.16.210.181,Posts,recipes,"Alpro ijskoffie",Deleted
2023/06/28 07:18:49   AM,unknown,52.16.210.181,Posts,recipes,"Alpro Soja   Cappuccino",Deleted
2023/06/28 07:18:50   AM,unknown,52.16.210.181,Posts,discover,"Ik wil gewoon een kopje   koffie!",Deleted
2023/06/28 07:18:50   AM,unknown,52.16.210.181,Posts,recipes,"Cereal Chocolate   Crunch",Deleted
2023/06/28 07:18:50   AM,unknown,52.16.210.181,Posts,recipes,"Havertastische   affogato",Deleted
2023/06/28 07:18:51   AM,unknown,52.16.210.181,Attachments,attachment,"Gust Coffee &#8211
2023/06/28 07:18:51   AM,unknown,52.16.210.181,Posts,recipes,"Koude   rozencappuccino",Deleted
2023/06/28 07:18:53   AM,unknown,52.16.210.181,Attachments,attachment,183458715_302296858148595_6291803537331518589_n,Deleted
2023/06/28 07:18:55   AM,unknown,52.16.210.181,Attachments,attachment,183458715_302296858148595_6291803537331518589_n,Deleted
2023/06/28 07:18:57   AM,unknown,52.16.210.181,Attachments,attachment,183458715_302296858148595_6291803537331518589_n,Deleted
2023/06/28 07:18:57   AM,unknown,99.80.255.172,Attachments,attachment,183458715_302296858148595_6291803537331518589_n,Deleted
2023/06/28 07:18:57   AM,unknown,99.80.255.172,Users,Profile,birgit-verheyen,Deleted
2023/06/28 07:19:00   AM,unknown,52.16.210.181,Attachments,attachment,183458715_302296858148595_6291803537331518589_n,Deleted
2023/06/28 07:19:00   AM,unknown,99.80.255.172,Attachments,attachment,183458715_302296858148595_6291803537331518589_n,Deleted
2023/06/28 07:19:02   AM,unknown,52.16.210.181,Attachments,attachment,183458715_302296858148595_6291803537331518589_n,Deleted
2023/06/28 07:19:02   AM,unknown,99.80.255.172,Attachments,attachment,183458715_302296858148595_6291803537331518589_n,Deleted
2023/06/28 07:19:04   AM,unknown,52.16.210.181,Attachments,attachment,"El Triunfo Gust   Coffee",Deleted
2023/06/28 07:19:05   AM,unknown,99.80.255.172,Attachments,attachment,"El Triunfo Gust   Coffee",Deleted
2023/06/28 07:19:05   AM,unknown,99.80.255.172,Attachments,attachment,triunfonew3_1080x,Deleted
2023/06/28 07:19:07   AM,unknown,52.16.210.181,Attachments,attachment,"Gust El   Triunfo",Deleted
2023/06/28 07:19:07   AM,unknown,99.80.255.172,Attachments,attachment,"Gust El   Triunfo",Deleted
2023/06/28 07:19:07   AM,unknown,99.80.255.172,Attachments,attachment,triunfonew3_1080x,Deleted
2023/06/28 07:19:10   AM,unknown,52.16.210.181,Attachments,attachment,triunfonew3_1080x,Deleted
2023/06/28 07:19:10   AM,unknown,99.80.255.172,Attachments,attachment,triunfonew3_1080x,Deleted
2023/06/28 07:19:12   AM,unknown,52.16.210.181,Attachments,attachment,triunfonew3_1080x,Deleted
2023/06/28 07:19:12   AM,unknown,99.80.255.172,Attachments,attachment,triunfonew3_1080x,Deleted
2023/06/28 07:19:14   AM,unknown,52.16.210.181,Attachments,attachment,triunfonew3_1080x,Deleted
2023/06/28 07:19:15   AM,unknown,52.16.210.181,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:15   AM,unknown,99.80.255.172,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:15   AM,unknown,99.80.255.172,Attachments,attachment,triunfonew3_1080x,Deleted
2023/06/28 07:19:17   AM,unknown,52.16.210.181,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:17   AM,unknown,99.80.255.172,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:19   AM,unknown,52.16.210.181,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:19   AM,unknown,99.80.255.172,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:21   AM,unknown,52.16.210.181,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:21   AM,unknown,99.80.255.172,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:23   AM,unknown,99.80.255.172,Attachments,attachment,107533117_141966614181621_7785234235954269460_n,Deleted
2023/06/28 07:19:24   AM,unknown,52.16.210.181,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:25   AM,unknown,99.80.255.172,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:26   AM,unknown,52.16.210.181,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:27   AM,unknown,52.16.210.181,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:27   AM,unknown,52.16.210.181,Users,Profile,birgit-verheyen,Deleted
2023/06/28 07:19:28   AM,unknown,52.16.210.181,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:28   AM,unknown,99.80.255.172,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:29   AM,unknown,52.16.210.181,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:30   AM,unknown,52.16.210.181,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:30   AM,unknown,99.80.255.172,Attachments,attachment,"our_obsession._your_coffee._1800x   (1)",Deleted
2023/06/28 07:19:31   AM,unknown,52.16.210.181,Attachments,attachment,logo,Deleted
2023/06/28 07:19:33   AM,unknown,52.16.210.181,Attachments,attachment,logo,Deleted
2023/06/28 07:19:33   AM,unknown,99.80.255.172,Attachments,attachment,logo,Deleted
2023/06/28 07:19:34   AM,unknown,52.16.210.181,Attachments,attachment,logo,Deleted
2023/06/28 07:19:36   AM,unknown,52.16.210.181,Attachments,attachment,logo,Deleted
2023/06/28 07:19:36   AM,unknown,99.80.255.172,Attachments,attachment,logo,Deleted
2023/06/28 07:19:37   AM,unknown,52.16.210.181,Attachments,attachment,logo,Deleted
2023/06/28 07:19:39   AM,unknown,52.16.210.181,Attachments,attachment,logo,Deleted
2023/06/28 07:19:39   AM,unknown,99.80.255.172,Attachments,attachment,logo,Deleted
2023/06/28 07:19:40   AM,unknown,52.16.210.181,Attachments,attachment,cuperus-el-carmen-nicaragua,Deleted
2023/06/28 07:19:41   AM,unknown,99.80.255.172,Attachments,attachment,cuperus-el-carmen-nicaragua,Deleted
2023/06/28 07:19:42   AM,unknown,52.16.210.181,Attachments,attachment,cuperus-el-carmen-nicaragua,Deleted
2023/06/28 07:19:43   AM,unknown,52.16.210.181,Attachments,attachment,cuperus-el-carmen-nicaragua,Deleted
2023/06/28 07:19:44   AM,unknown,99.80.255.172,Attachments,attachment,cuperus-el-carmen-nicaragua,Deleted
2023/06/28 07:19:45   AM,unknown,52.16.210.181,Attachments,attachment,cuperus-el-carmen-nicaragua,Deleted
2023/06/28 07:19:47   AM,unknown,52.16.210.181,Attachments,attachment,cuperus-el-carmen-nicaragua,Deleted
2023/06/28 07:19:47   AM,unknown,99.80.255.172,Attachments,attachment,cuperus-el-carmen-nicaragua,Deleted
2023/06/28 07:19:48   AM,unknown,52.16.210.181,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:49   AM,unknown,52.16.210.181,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:50   AM,unknown,52.16.210.181,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:50   AM,unknown,99.80.255.172,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:51   AM,unknown,52.16.210.181,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:51   AM,unknown,99.80.255.172,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:52   AM,unknown,52.16.210.181,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:53   AM,unknown,52.16.210.181,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:53   AM,unknown,99.80.255.172,Attachments,attachment,"hoe maak je de perfecte   espresso artikel",Deleted
2023/06/28 07:19:54   AM,unknown,52.16.210.181,Attachments,attachment,"Koude   rozencappuccino",Deleted
2023/06/28 07:19:55   AM,unknown,52.16.210.181,Attachments,attachment,"Cold Rose   Cappuccino",Deleted
2023/06/28 07:19:55   AM,unknown,99.80.255.172,Attachments,attachment,"Cold Rose   Cappuccino",Deleted
2023/06/28 07:19:56   AM,unknown,99.80.255.172,Attachments,attachment,"Cold Rose   Cappuccino",Deleted
2023/06/28 07:19:57   AM,unknown,52.16.210.181,Attachments,attachment,"Cold Rose   Cappuccino",Deleted
2023/06/28 07:19:58   AM,unknown,52.16.210.181,Attachments,attachment,"Cold Rose   Cappuccino",Deleted
2023/06/28 07:19:58   AM,unknown,99.80.255.172,Attachments,attachment,"Cold Rose   Cappuccino",Deleted

52.16.210.181 and 99.80.255.172 are the two IP from an external server (in this case Amazon). I search in more or less one years of log and sometimes this two IP deleted some users, but last week they do something like what I entered above.


I thought about hackers, but I assume they would have taken over the site and not done such a thing

**Comment by StefsterNYC** [comment]
Thanks for this. You're positive none of these deletions are coming from users that have access to the site? For instance the first few the User deleted etc

**Comment by Maxbonesso** [comment]
Yes, I'm sure, also because there are 4 admins on this site and they are my colleagues, they didn't do this
The deleted profile was a shop manager and every content deleted was about his specific language (the site use WPML and have a lot of language), but not posts or somethings that this profile created/loaded on the site

**Comment by StefsterNYC** [comment]
Ah, I was just about to say,  if you deleted a user who created posts/pages etc, you deleted those as well if you didn't attribute them to someone else when deleting/removing that user. So good to know you didn't. Ya hard to say.

**Comment by Maxbonesso** [comment]
Server side I didn't find any dump or query to download data or fraudulent access, so on that side I'm calm. I changed every password of editor, shop customer and admin (the site has also 2FA active for Wordpress backend).
Is there a way to block this type of activity? I blocked this two IP but they are "server IP" so it's a partial block
