### ISSUE TITLE
Plugin must be hacked, it keeps advertising Elementor to me

### ISSUE THREAD

**Issue by mwaterous** [pojome/activity-log#184]
I can't imagine why Activity Log would be spamming Elementor on my dashboard, and worse, doing so in such a way that can't be permanently dismissed. I can only assume your codebase has been hacked by the Elementor team, or perhaps by an over zealous fan of garbage software that turns your website into a pile of div soup.

I'm happy to submit a pull request removing this awful mistake, if you're too busy to remove it yourself?

**Comment by arielk** [comment]
This issue has been resolved in the recently updates. Feel free to update. 

Thanks!
