### ISSUE TITLE
App is Hiding WooCommerce Save Button In Payment Gateway UI

### ISSUE THREAD

**Issue by serafintechnology** [pojome/activity-log#194]
We noticed this just now on one client's site. Once app is enabled the blue Save button disappears. Checking other clients with WooCommerce now.

![492ed93d365e4a19beddb4090754bbd8](https://github.com/pojome/activity-log/assets/114924454/986ab3dc-e8cc-47a6-a5e9-3816eab18f5d)

**Comment by fschuermeyer** [comment]
Have the same issue, with the newest Version 2.8.8 and Woocommerce Version: 8.2.2
I have the Issue on any Woocommerce Page with a Save Button.

**Comment by arielk** [comment]
@fschuermeyer For some reason we are unable to reproduce this issue in our dev environment. Could you please share with us the steps to reproduce this situation?

**Comment by fschuermeyer** [comment]
Unfortunately it is not so easy, the plugin is not installed regularly but via the mu-plugins folder, according to its own logic, as well as Woocommerce itself.

So far I could see that it has to do with the include of the Woocommerce integration. And there with the hook from line 14. 

https://github.com/pojome/activity-log/blob/master/classes/class-aal-integration-woocommerce.php#L14

I can have another look in the next few days to see if I can find the right solution.

**Comment by arielk** [comment]
Right now, we've taken out the feature that tracks the WC settings to avoid this problem. Thanks for letting us know your thoughts!
