### ISSUE TITLE
WordPress database error:[Illegal mix of collations / SELECT `histid` FROM `wpop_aryo_activity_log

### ISSUE THREAD

**Issue by oldrup** [pojome/activity-log#196]
I uploaded a png to the media library with a horrible, horrible filename, and WP_DEBUG replied with an error:

`WordPress database error: [Illegal mix of collations (utf8mb3_general_ci,IMPLICIT) and (utf8mb4_unicode_520_ci,COERCIBLE) for operation '=']
SELECT `histid` FROM `wpop_aryo_activity_log` WHERE `user_caps` = 'administrator' AND `action` = 'updated' AND `object_type` = 'Attachments' AND `object_subtype` = 'attachment' AND `object_name` = 'bastard æøå ÆØÅ !#$ &#8216;😀😁😂&#8217;' AND `user_id` = '1' AND `hist_ip` = 'xx.xx.xx.xx' AND `hist_time` = '1698923451' ;`

Filename: `bastard æøå ÆØÅ !#$ '😀😁😂'`

Is that something you can reproduce?

![image](https://github.com/pojome/activity-log/assets/17141205/62c88ba5-8bbb-4566-8485-74dd973d3786)

Not critical; the file is being uploaded and the action registered in the log.

WordPress 6.4 RC3 and PHP 8.2

**Comment by KingYes** [comment]
Hi @oldrup,
I tried to reproduce your issue, but I need help.

I created a media filename with `bastard æøå ÆØÅ !#$ '😀😁😂'`, and I uploaded it to the WP media. And all works just fine.

Feel free to reopen this issue if you know how to reproduce it.

**Comment by oldrup** [comment]
That's good @KingYes - then it's not a widespread issue. _Maybe_ some legacy database character set thingy messing with me.

I'll see if it's an issue on my other sites.

Thank you so much for taking the time to test this.
