### ISSUE TITLE
Introduce filters in the aal_insert_log() function

### ISSUE THREAD

**Issue by asafm7** [pojome/activity-log#201]
Introduce filters in the aal_insert_log() function.

This can allow more flexibility.

Between the rest, it can allow to short-circuit the function under specific conditions.

I, for example, look for a way to exclude post-draft changes from the log, as they flood it.

**Comment by KingYes** [comment]
If you want to skip from the log, you can use that filter: https://github.com/pojome/activity-log/pull/209
