### ISSUE TITLE
Recommend running the aal_skip_insert_log filter before the duplicates check SQL query

### ISSUE THREAD

**Issue by petenelson** [pojome/activity-log#208]
The [check for duplicate records ](https://github.com/pojome/activity-log/blob/master/classes/class-aal-api.php#L102) is running before the `aal_skip_insert_log` filter is being fired, but if the filter could be preventing inserts anyway, there is no reason to check for duplicates.

I'd recommend running that filter before the duplicate check query. On a large number of records, that could unnecessarily slow down the function call. Very grateful the new `aal_skip_insert_log` filter was added recently, as we found about 1 million extra records in our log recently cause by our own internal logging plugin. Any time we'd make our own log entry (a custom post type), the Activity Log plugin also recorded the log entry being created, and we didn't need it duplicated. We were able to modify our plugin and prevent this behavior.

**Comment by KingYes** [comment]
Hi @petenelson 

1) You're right, thanks for your feedback!
2) If you have the old installed plugin, I recommend you to re-index by these indexes: https://github.com/pojome/activity-log/blob/d160e2ff297e4bf96639217fec750a799ad7df62/classes/class-aal-maintenance.php#L59-L79
