### ISSUE TITLE
Filter by IP

### ISSUE THREAD

**Issue by KingYes** [pojome/activity-log#65]
From [WordPress support](http://wordpress.org/support/topic/filter-by-ip):

> Is there a way to filter log entries by IP to see what all requests are coming from single IP?
> - [romancos](http://wordpress.org/support/profile/romancos)

**Comment by rvola** [comment]
Hi !
This functionality has been partially implemented.
With the following fix [#107](https://github.com/KingYes/wordpress-aryo-activity-log/pull/107) it works
